name: example
description: A minimal jaspr web app.
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  jaspr:
    git:
      url: https://github.com/mjablecnik/jaspr.git
      path: packages/jaspr
      ref: bootstrap-components
  jaspr_ui:
    path: ../

dev_dependencies:
  build_runner: ^2.1.11
  build_web_compilers: ^3.2.3
  lints: ^2.0.0
  webdev: ^2.7.9
