name: riverpod_app
description: An absolute bare-bones web app.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  jaspr: ^0.3.0
  jaspr_riverpod: ^0.2.3

dev_dependencies:
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  jaspr_builder: ^0.2.0
  lints: ^2.0.1
