include: package:lints/recommended.yaml

# TODO: remove this
analyzer:
  exclude:
    - lib/src/ui/_ui

linter:
  rules:
    sort_pub_dependencies: true
    prefer_relative_imports: false
    directives_ordering: true