name: jaspr_project

packages:
  - packages/**
  - experiments/**
  - demo/**

scripts:
  analyze: melos exec -- "dart analyze ."
  tools:
    name: tools
    run: melos exec -- "dart run $MELOS_ROOT_PATH/tools/bin/tools.dart"
    select-package: {}