name: jaspr_project

packages:
  - packages/**
  - experiments/**
  - demo/**

scripts:
  analyze: melos exec -- "dart analyze ."
  jaspr:
    name: jaspr
    run: melos exec -- "dart run jaspr"
    select-package:
      riverpod: true