name: dart_web
version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  domino: ^0.8.0
  shelf: ^1.2.0
  meta: ^1.7.0
  shelf_proxy: ^1.0.1
  hotreloader: ^3.0.2
  shelf_static: ^1.1.0
  args: ^2.3.0

dev_dependencies:
  build_runner: ^2.1.7
  build_web_compilers: ^3.2.2
  lints: ^1.0.1
