name: dart_web

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  domino: ^0.8.0
  shelf: ^1.2.0
  shelf_static: ^1.1.0
  shelf_hotreload: ^1.0.1
  meta: ^1.7.0
  build_daemon: ^3.0.1
  http: ^0.13.4
  shelf_proxy: ^1.0.1
  webdev: ^2.7.7

dev_dependencies:
  build_runner: ^2.1.7
  build_web_compilers: ^3.2.2
  lints: ^1.0.1
