name: dart_frog_backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_frog: ^0.2.0
  jaspr: ^0.1.0

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  jaspr_builder: ^0.1.0
  lints: ^2.0.1
