name: {{name}}
description: A classic web app using separate html, css and dart files with ssr & manual client hydration.
version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  jaspr: ^{{jasprCoreVersion}}

dev_dependencies:
  build_runner: ^2.2.0
  build_web_compilers: ^3.2.1
  lints: ^2.0.1
  webdev: 2.7.7