name: jaspr_serverpod
description: Serverpod integration for jaspr.
version: 0.3.3
homepage: https://github.com/schultek/jaspr
issue_tracker: https://github.com/schultek/jaspr/issues
documentation: https://docs.page/schultek/jaspr
funding:
  - https://github.com/sponsors/schultek

topics:
  - jaspr
  - web
  - serverpod

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.15.0
  serverpod: 2.1.1
  serverpod_client: 2.1.1
  shelf: ^1.4.0
  web: ^1.0.0

dev_dependencies:
  lints: ^4.0.0
