name: {{name}}
description: A pure client-side app without ssr.
version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  jaspr: ^{{jasprCoreVersion}}

dev_dependencies:
  build_runner: ^2.2.0
  build_web_compilers: ^3.2.1
  lints: ^2.0.1
