name: dart_quotes_server
description: Collection of Dart quotes.
version: 0.1.2
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  dart_quotes_client:
    path: ./client
  jaspr: ^0.15.1
  jaspr_router: ^0.5.1
  jaspr_serverpod: ^0.3.3
  serverpod: 2.1.1
  serverpod_auth_google_flutter: 2.1.1
  serverpod_auth_server: 2.1.1
  serverpod_auth_shared_flutter: 2.1.1
  serverpod_serialization: 2.1.1

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.0.10
  jaspr_builder: ^0.15.1
  lints: ^4.0.0

jaspr:
  mode: server
  dev-command: dart bin/main.dart --apply-migrations
