name: dart_quotes_server
description: Collection of Dart quotes.

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  dart_quotes_client:
    path: ./client
  jaspr: ^0.13.0
  jaspr_router: ^0.4.2
  jaspr_serverpod: ^0.1.0
  serverpod: 1.2.7
  serverpod_auth_google_flutter: ^1.1.1
  serverpod_auth_server: 1.2.7
  serverpod_auth_shared_flutter: ^1.1.1
  serverpod_serialization: 1.2.7

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.0.9
  jaspr_builder: ^0.13.0
  lints: ^3.0.0

jaspr:
  mode: server
  dev-command: dart bin/main.dart
