name: jaspr_lints
description: A customer linter package for the Jaspr framework 
version: 0.1.0 
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  analyzer: ^5.4.0
  analyzer_plugin: ^0.11.0
  custom_lint_builder: ^0.5.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
