name: dart_quotes
description: A new jaspr project.
version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  firebase_core: ^2.31.0
  jaspr: ^0.12.0
  jaspr_router: ^0.4.1
  cloud_firestore: 4.17.1
  dart_firebase_admin: ^0.3.1
  _flutterfire_internals: 1.3.31
  firebase_auth: ^4.19.3

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.0.9
  jaspr_builder: ^0.12.0
  lints: ^3.0.0

dependency_overrides:
  jaspr:
    git:
      url: https://github.com/schultek/jaspr
      path: packages/jaspr
  jaspr_builder:
    git:
      url: https://github.com/schultek/jaspr
      path: packages/jaspr_builder

jaspr:
  mode: server

