name: dart_quotes
description: A collection of Dart quotes. Built for FullStackFlutter Conference.
version: 0.1.2
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  firebase_core: ^3.3.0
  jaspr: ^0.15.0
  jaspr_router: ^0.5.1
  cloud_firestore: ^5.2.1
  dart_firebase_admin: ^0.3.1
  firebase_auth: ^5.1.4

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.0.10
  jaspr_builder: ^0.15.0
  lints: ^4.0.0

dependency_overrides:
  # Remove when updating firebase_auth to new version.
  web: ^1.0.0

jaspr:
  mode: server

