name: dart_quotes
description: A collection of Dart quotes. Built for FullStackFlutter Conference.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  firebase_core: ^2.31.0
  jaspr: ^0.13.0
  jaspr_router: ^0.4.2
  cloud_firestore: 4.17.1
  dart_firebase_admin: ^0.3.1
  _flutterfire_internals: 1.3.31
  firebase_auth: ^4.19.3

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.0.9
  jaspr_builder: ^0.13.0
  lints: ^3.0.0

jaspr:
  mode: server

