name: jaspr_pad
description: Dartpad inspired online-editor for jaspr built with jaspr
version: 0.1.0

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  codemirror: ^0.7.3+5.65.2
  jaspr: ^0.1.0

dev_dependencies:
  build_runner: ^2.1.7
  build_web_compilers: ^3.2.2
  lints: ^1.0.0
  mdc_web: ^0.6.0
  test: ^1.16.0
  jaspr_builder: ^0.1.0
  jaspr_test: ^0.1.0

dependency_overrides:
  jaspr: 
    path: ../jaspr
  jaspr_test: 
    path: ../jaspr_test
  jaspr_builder: 
    path: ../jaspr_builder