name: jaspr_pad
description: Dartpad inspired online-editor for jaspr built with jaspr
version: 0.1.0

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  analysis_server_lib: ^0.2.2
  codemirror: ^0.7.3+5.65.2
  dart_mappable: ^1.1.0
  jaspr: ^0.1.0
  jaspr_riverpod: ^0.1.0
  shelf_router: ^1.1.2

dev_dependencies:
  build_runner: ^2.1.7
  build_web_compilers: ^3.2.2
  lints: ^1.0.0
  mdc_web: ^0.6.0
  test: ^1.16.0
  jaspr_builder: ^0.1.0
  jaspr_test: ^0.1.0
  dart_mappable_builder: ^1.1.0
  yaml_writer: ^1.0.1

dependency_overrides:
  jaspr: 
    path: ../jaspr
  jaspr_test: 
    path: ../jaspr_test
  jaspr_builder: 
    path: ../jaspr_builder
  jaspr_riverpod:
    path: ../jaspr_riverpod