name: example_server
description: Starting point for a Serverpod server.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.15.0
  jaspr_serverpod: ^0.3.2
  serverpod: 2.1.1

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  jaspr_builder: ^0.15.0
  lints: ^3.0.0

jaspr:
  mode: server
  dev-command: dart bin/main.dart --apply-migrations
