name: jaspr_riverpod
description: Riverpod for jaspr
version: 0.1.0

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  riverpod: ^2.0.0-dev.4
  jaspr:
    path: ../jaspr

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
