name: jaspr_riverpod
description: Riverpod for Jaspr
version: 0.3.11
homepage: https://github.com/schultek/jaspr
issue_tracker: https://github.com/schultek/jaspr/issues

topics:
  - jaspr
  - web

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.12.0
  meta: ^1.9.1
  riverpod: ^2.4.8

dev_dependencies:
  jaspr_test: '>=0.1.0 <1.0.0'
  lints: ^3.0.0
  test: ^1.24.1
