name: jaspr_riverpod
description: Riverpod for Jaspr
version: 0.3.1
homepage: https://github.com/schultek/jaspr
issue_tracker: https://github.com/schultek/jaspr/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.4.0
  meta: ^1.9.1
  riverpod: ^2.3.2

dev_dependencies:
  jaspr_test: ^0.3.0
  lints: ^2.1.0
  test: ^1.24.1
