name: jaspr_riverpod
description: Riverpod for Jaspr
version: 0.2.3
homepage: https://github.com/schultek/jaspr
issue_tracker: https://github.com/schultek/jaspr/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  jaspr: ^0.3.0
  meta: ^1.9.1
  riverpod: ^2.3.2

dev_dependencies:
  jaspr_test: ^0.2.0
  lints: ^2.0.1
  test: ^1.24.1
