builders:
  jaspr_builder:islands:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildIslands" ]
    build_extensions: { "lib/$lib$": [ "web/main.islands.dart" ] }
    auto_apply: dependents
    build_to: source
    runs_before:
      - build_web_compilers
  jaspr_builder:apps:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildApps" ]
    build_extensions: { "^lib/{{file}}.dart": [ "lib/{{file}}.g.dart", "web/{{file}}.app.dart", "web/{{file}}.island.dart" ] }
    auto_apply: dependents
    build_to: source
    runs_before:
      - jaspr_builder:apps
      - build_web_compilers
  jaspr_builder:imports:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "findPlatformImports" ]
    build_extensions: { ".dart": [ ".imports.json" ] }
    auto_apply: dependents
    build_to: cache
    runs_before: [ "build_web_compilers", ":import_parts" ]
    applies_builders: [ ":stub" ]
  jaspr_builder:import_parts:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "writePlatformImports" ]
    build_extensions: { ".import.json": [ ".imports.dart" ] }
    auto_apply: dependents
    build_to: source
    runs_before: [ "build_web_compilers" ]
    applies_builders: [ ":stub" ]
  jaspr_builder:stub:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildPlatformStubs" ]
    build_extensions: { "lib/$lib$": [
      "lib/generated/imports/_web.dart",
      "lib/generated/imports/_vm.dart",
      "lib/generated/imports/_stubs.dart"
    ] }
    auto_apply: dependents
    build_to: source
    runs_before: [ "build_web_compilers" ]
targets:
  $default:
    builders:
      jaspr_builder:
        generate_for:
          - test/native_interfaces.web.dart
