builders:
  jaspr_builder:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildWebFake" ]
    build_extensions: { ".web.dart": [ ".stub.dart", ".dart" ] }
    auto_apply: dependents
    build_to: source
targets:
  $default:
    builders:
      jaspr_builder:
        generate_for:
          - test/native_interfaces.web.dart
