builders:
  jaspr_builder:islands:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildIslands" ]
    build_extensions: { "lib/$lib$": [ "web/main.islands.dart" ] }
    auto_apply: dependents
    build_to: source
    runs_before:
      - build_web_compilers
  jaspr_builder:apps:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildApps" ]
    build_extensions: { "^lib/{{file}}.dart": [ "lib/{{file}}.g.dart", "web/{{file}}.app.dart", "web/{{file}}.island.dart" ] }
    auto_apply: dependents
    build_to: source
    runs_before:
      - jaspr_builder:apps
      - build_web_compilers
  jaspr_builder:web_mock:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildWebMock" ]
    build_extensions: { ".web.dart": [ ".stub.dart", ".dart" ] }
    auto_apply: dependents
    build_to: source
    runs_before:
      - build_web_compilers
targets:
  $default:
    builders:
      jaspr_builder:
        generate_for:
          - test/native_interfaces.web.dart
