builders:
  clients:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildClient" ]
    build_extensions: {
      "^lib/{{file}}.dart": [ "lib/{{file}}.g.dart", "web/{{file}}.client.dart" ],
    }
    auto_apply: dependents
    build_to: source
  registry:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildRegistry" ]
    build_extensions: {
      "lib/$lib$": [ "web/main.clients.dart" ],
    }
    auto_apply: dependents
    build_to: cache
    required_inputs:
      - '.client.dart'
  imports:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "findPlatformImports" ]
    build_extensions: { ".dart": [ ".imports.json" ] }
    auto_apply: dependents
    build_to: cache
    runs_before:
      - :import_parts
    applies_builders: [ ":stub" ]
  import_parts:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "writePlatformImports" ]
    build_extensions: { ".imports.json": [ ".imports.dart" ] }
    auto_apply: dependents
    required_inputs:
      - '.imports.json'
    build_to: source
    runs_before:
      - :stub
    applies_builders: [ ":stub" ]
  stub:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildPlatformStubs" ]
    build_extensions: { "lib/$lib$": [
      "lib/generated/imports/_web.dart",
      "lib/generated/imports/_vm.dart",
      "lib/generated/imports/_stubs.dart"
    ] }
    auto_apply: dependents
    required_inputs:
      - .imports.json
    build_to: source
