builders:
  jaspr_builder:entrypoint:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildEntrypoint" ]
    build_extensions: { ".dart": [ ".g.dart" ] }
    auto_apply: dependents
    build_to: source
    runs_before:
      - build_web_compilers
    defaults:
      generate_for:
        - lib/main.dart
  jaspr_builder:apps:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildApps" ]
    build_extensions: { "^lib/{{file}}.dart": [ "web/{{file}}.g.dart" ] }
    auto_apply: dependents
    build_to: source
    runs_before:
      - build_web_compilers
  jaspr_builder:web_mock:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildWebMock" ]
    build_extensions: { ".web.dart": [ ".stub.dart", ".dart" ] }
    auto_apply: dependents
    build_to: source
    runs_before:
      - build_web_compilers
  jaspr_builder:island:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildIsland" ]
    build_extensions: { ".dart": [ ".island.g.dart" ] }
    auto_apply: dependents
    build_to: source
    runs_before:
      - build_web_compilers
  jaspr_builder:islands_app:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildIslandsApp" ]
    build_extensions: { "main.dart": [ "islands.g.dart", ] }
    auto_apply: dependents
    build_to: source
    required_inputs: [ ".island.dart" ]
    runs_before:
      - build_web_compilers
    defaults:
      generate_for:
        - lib/main.dart
targets:
  $default:
    builders:
      jaspr_builder:
        generate_for:
          - test/native_interfaces.web.dart
