name: jaspr_builder
description: Builders for jaspr
version: 0.14.0
homepage: https://github.com/schultek/jaspr
issue_tracker: https://github.com/schultek/jaspr/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

topics:
  - jaspr
  - web
  - codegen
  - build-runner

dependencies:
  analyzer: ^6.5.0
  build: ^2.0.0
  collection: ^1.15.0
  dart_style: ^2.2.3
  glob: ^2.1.1
  jaspr: ^0.14.0
  path: ^1.8.0
  source_gen: ^1.2.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.0
  build_test: ^2.2.2
  lints: ^3.0.0
  test: ^1.22.0
