on:
  workflow_dispatch:

name: Publish Packages

jobs:
  release:
    name: Publish Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: dart-lang/setup-dart@v1.3

      - name: Bootstrap
        run: |
          dart pub global activate melos
          melos bootstrap

      - name: Publish Packages
        run: |
          version publish
