on:
  workflow_dispatch:
  push:
    branches:
      - stable
    paths:
      - '.github/workflows/release.yml'
      - 'packages/**'

name: Release Pipeline

jobs:
  release:
    name: Bump Packages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PUSH_TOKEN }}

      - uses: dart-lang/setup-dart@v1.3

      - name: Bootstrap
        run: |
          dart pub global activate melos
          dart pub global activate -s git https://github.com/schultek/semantic_changelog
          melos bootstrap --no-private

      - name: Bump Package Versions
        id: bump
        run: |
          version bump --scope="packages/*" | tee output.txt
          echo 'commit_message<<EOF' >> $GITHUB_OUTPUT
          echo "Bump package versions" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          cat output.txt >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
          echo "did_bump=$(grep -q "No packages" output.txt; echo $?)" >> $GITHUB_OUTPUT
          rm -rf output.txt

      - name: Update CLI
        run: |
          melos generate:versions
          melos format

      - name: Commit Versions
        if: steps.bump.outputs.did_bump != '0'
        run: |
          git add .
          git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
            commit -m "${{ steps.bump.outputs.commit_message }}" \
            --author="${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"

      - name: Tag Packages
        run: |
          version tag -f
          git push --tags origin

