on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/test.yml'
      - 'packages/**'

name: Test Pipeline

jobs:
  cli:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    name: Verify CLI Tool
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1.3

      - name: Bootstrap
        run: |
          dart pub global activate melos
          melos bootstrap --no-private

      - name: Create & Build Project
        run: |
          cd apps
          jaspr create -t basic my_app
          melos bootstrap
          cd my_app
          jaspr build

  analyze:
    name: Analyze Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@v1.3

      - name: Bootstrap
        run: |
          dart pub global activate melos
          melos bootstrap

      - name: Check formatting
        run: melos format -- --set-exit-if-changed

      - name: Check linting
        run: melos analyze

  test:
    name: Test Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@v1.3

      - name: Bootstrap
        run: |
          dart pub global activate melos
          dart pub global activate coverage
          melos bootstrap --no-private

      - name: Run Unit tests
        run: melos coverage:ci

      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          files: coverage/*_lcov.info

  report:
    name: Version Report
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@v1.3

      - name: Bootstrap
        run: |
          dart pub global activate melos
          dart pub global activate -s git https://github.com/schultek/semantic_changelog
          melos bootstrap --no-private

      - name: Bump Package Versions
        id: bump
        run: |
          version bump --dry-run --scope="packages/*" | tee output.txt
          echo 'version_report<<EOF' >> $GITHUB_OUTPUT
          echo '## Package Version Report' >> $GITHUB_OUTPUT
          cat output.txt >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
          rm -rf output.txt

      - name: Create PR comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: ${{ steps.bump.outputs.version_report }}
          comment_tag: version_report
