name: shelf_handler
description: An absolute bare-bones web app.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  jaspr: ^0.1.0
  shelf: ^1.3.1
  shelf_router: ^1.1.3

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  jaspr_builder: ^0.1.0
  lints: ^1.0.0
